print("How old are you?", end=' ')
age = input()
print("How tall are you?", end=' ')
height = input()
print("How much do you weigh?", end=' ')
weight = input()

print(f"So, you're {age} years old, {height} tall and {weight} lbs heavy.")
print("Is this information correct? Yes or No", end=' ')
input()
print("Great, thank you.  Really quickly before we continue are you a boy or girl?", end=' ')
input()
print("A girl!  I haven't ever been touched by a woman.  What is your name?", end=' ')
name = input()
print(f"OK, {name} I've got a few more questions is that OK? Yes or No", end=' ')
input()
print("Great.  How big is your rack?", end=' ')
breast_size = input()
print(f"Holy flesh cannons {name}.  How about your waist size for a ballroom gown?", end=' ')
waist_size = input()
print("Just a couple more questions for my algorithm.  Do you have a nice butt?", end=' ')
input()
print(f"Wow {name} you sound hot!  Is there something wrong with you face?  Are you a troll face or something?", end=' ')
input()
print("OK.  Let me process all this information.  Really quick, while I am processing this information have you enjoyed your experience?", end=' ')
final_decision = input()
print(f"So, {name}, you are {age} years old, {height} tall, {weight} lbs heavy, with {breast_size} tits, a size {waist_size} waist, a sweet ass, and you're not a troll face? Is this correct?", end=' ')
input()
print(f"Great.  My program has finished running and to the question: Are you approved for sex with my owner the answer is: {final_decision}")
print("Congratulations.  Please undress.")
